### ISSUE TITLE
<ushort> and <ushort> ... can produce some Headhake ;-)

### ISSUE THREAD

**Issue by SilNak** [tpierrain/NFluent#138]
Consider the following:
`            ushort usValue = 2;
            int iValue = 1;
            Check.That(usValue).IsEqualTo<ushort>(iValue + 1);`

nFluent Error Message Factory (EMF) is grumpy:

> NFluent.FluentCheckException: 
The checked value is different from the expected one.
The checked value:
	[2] of type: [ushort]
The expected value:
	[2] of type: [int]

A tentative to make it happy with:
`            ushort usValue = 2;
            int iValue = 1;
            Check.That<ushort>(usValue).IsEqualTo<ushort>(iValue + 1);`

Now way, the EMF is still Grumpy (he is french or what!):

> NFluent.FluentCheckException: 
The checked value is different from the expected one.
The checked value:
	[2] of type: [ushort]
The expected value:
	[2] of type: [int]

Has any good french ;-), we need to workaround with the truth:
`            ushort usValue = 2;
            int iValue = 1;
            Check.That<int>(usValue).IsEqualTo<int>(iValue + 1);`

A straightaway syntax would be fine:
 `            ushort usValue = 2;
            int iValue = 1;
            Check.That(usValue).IsEqualTo(iValue + 1);`

**Comment by dupdob** [comment]
I propose not to change the current behavior: 
in your example, _iValue+1_ is automatically 'upgraded' to **int** because _1_ is an **int**.

During the initial behavior discussions for numerical checks, we **decided that the precise type was a natural part of the expected value** and that most developers would prefer to have to precisely specify the type.

So, I will implement **an improved error message** to cover the case where **checked and expected have the same value with different type**.

**Comment by dupdob** [comment]
See issue #153

**Comment by SilNak** [comment]
Fine for me!

**Comment by dupdob** [comment]
Well, everybody learns. 
After careful considerations, we reversed our decisions. So I am happy to say that a fix has been implemented and is part of my current PR (see PR #155)
