### ISSUE TITLE
Explicit Fail Message

### ISSUE THREAD

**Issue by Ouarzy** [tpierrain/NFluent#166]
Hi guyz,

A little improvement that may be more user friendly when we have a few thousands tests to track, may be to add an explicit message when a test fail.

For example the default message when this test :
`Check.That(person.HasAName).IsTrue();
`
Fail is:

> "The checked boolean is false whereas it must be true."

I would prefer Something like:

>  "The person has no name"

It would be a feature similar to this code in Xunit:
`Assert.True(person.HasAName, "The person has no name");`

I am still looking for a fluent syntax for that.
What about:
`Check.That(person.HasAName).IsTrue().DisplayOnFailure("The person has no name");
`

**Comment by tpierrain** [comment]
Thanks @Ouarzy .  We're currently working on dotnet core port, but will iterate on that pull request afterwards to find the best syntax for this feature.

**Comment by dupdob** [comment]
Hi everyone
the philosophy of NFluent, regarding error messages, is to help pinpoint the cause of the error. In that sense, it is more technical than business domain. That being said: boolean should be true instead of false if a very weak message, agree. So improvement would be warmly welcomed.

Regarding your example, I have the impression it should belong the **test name**, not the error message. Something along the line of:
```c#
[Test]
public void ShouldHaveAName()
{
   Check.That(person.HasAName).IsTrue();
}
```
What is your opinion?

In any case, you can try the **As** keyword that we have just made available in the 2.0 pre release.
It allows you to specify/override the _sut_ name.
E.g.:
```c#
  Check.That(false).As("Name is present").IsTrue();
```
will output this message
> "The checked [Name is present] is false whereas it must be true."

What do you think?

**Comment by Ouarzy** [comment]
Yep, the As feature is usefull at least for me :)

I agree with your opinion about good name for test but:

- I still ahve to deal with legacy
- For integration tests, it is rarely performant to run one test per check

**Comment by marcin-chwedczuk-cybervadis** [comment]
I also agree with @Ouarzy, I have following assertion in my test code:
```csharp
        private static void CheckThatErrorIsPresentForField(
            ValidationResult validationResult, string fieldName)
        {
            Check.That(validationResult.IsValid).IsTrue();

            Check.That(validationResult.Errors)
                .HasElementThatMatches(error => error.PropertyName == fieldName);
        }
```
I would like to get more meaningful error message when first assertion fails instead of: `The checked boolean is false whereas it must be true`. Of course I know that it is generally considered a good practice to have only single assertion per test, but we all know that sometimes it is more pragmatic to have tests a few assertions. You may get some inspiration from AssertJ library (http://joel-costigliola.github.io/assertj/assertj-core-features-highlight.html#describe-assertion):
```java
TolkienCharacter frodo = new TolkienCharacter("Frodo", 33, HOBBIT);
 // failing assertion, remember to call as() before the assertion, not after !
 assertThat(frodo.getAge()).as("check %s's age", frodo.getName()).isEqualTo(100);
```
and the resulting error message:
```
[check Frodo's age] expected:<100> but was:<33>
```

**Comment by dupdob** [comment]
_As_ already exists in NFluent (see the [wiki](https://github.com/tpierrain/NFluent/wiki/Custom-Messages#as)). Can't remember when it was added, but it has been there for quite some time now. 
It does not support string formatting like its java counterpart, but I do not think this is an issue.

Using the sample you provide, one could use:
```csharp
            Check.That(validationResult.IsValid).As("Validity status").IsFalse();
```
It could raise:
The checked [validity status] is true whereas it must be false.

**Comment by marcin-chwedczuk-cybervadis** [comment]
Of course you are right, I don't know how I could miss it. Thank you for quick response.

**Comment by dupdob** [comment]
Well, your remark made me realize I forgot to describe _As(...)_ in the wiki. So this page is brand new, you could not have seen it before 😋

**Comment by Ouarzy** [comment]
Looks good to me, clearer than the "as" syntax :)

**Comment by dupdob** [comment]
__As__ serves a different purpose

**Comment by dupdob** [comment]
Added support to custom message for:
Check.ThatEnum and Check.ThatCode
