### ISSUE TITLE
Assertions on IDictionary are broken (and too limited)

### ISSUE THREAD

**Issue by henryju** [tpierrain/NFluent#178]
Hi,

First of all, I'm a Java developer, so I'm sorry if the words I'm using are not the appropriate one.

I was trying to use NFluent to do some assertions on an IDictionary<string, string>. First of all, I got compilation issue as long as the object I'm testing is of type IDictionary<string, string>. Changing it's type to Dictionary<string, string> fixed the issue, but that's seem to be a generic type issue.
Error message is:
'ICheck<IDictionary<string, string>>' does not contain a definition for 'ContainsValue' and the best extension method overload 'DictionaryCheckExtensions.ContainsValue<string>(ICheck<IDictionary>, string)' requires a receiver of type 'ICheck<IDictionary>'

My other concern is that I'm missing an assertion to very presence of key + value.

**Comment by dupdob** [comment]
Hello
thanks for pointing that out.
Indeed, checks were defined on then IDictionary interface and while Dictionary implements IDictionnary, the generic interfaces do not. We need to add signature for those.

**Comment by dupdob** [comment]
Hello again, after a bit of digging I realize this issue comes from the BCL class hierarchy. More specifically, there is no inheritance between IDictionary and IDictionary<K,V>.
Dictionary<K,V> to implement both interfaces.

Currently, NFluent supports IDictionary interface for checks; the bad news is that we cannot simply add support for IDictionary<K,V> as it leads to ambiguous calls when using DIctionary (and other classes). I added issue #179 to implement the migration.

Regarding your second requirement, can you please confirm having something like 
`Check.That(_myDictionary_).ContainsEntry(_key_,_value_)
is suitable?

**Comment by dupdob** [comment]
Migration to IDictionary<K, V> done in git
